env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    dir: ./cmd/gon/

archives:
  - id: macos-zip
    format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - 'README'

release:
  ids:
    - none
  extra_files:
    - glob: ./dist/gon_macos.zip
